### ISSUE TITLE
Add calendar feed to website 

### ISSUE THREAD

**Issue by albertkun** [UNopenGIS/smartmaps#20]
### Purpose

It would be good to communicate our Smart Maps events calendar on the website with the Google Calendar source!

**Comment by albertkun** [comment]
With #50 #51 

@hfu I've automated the generation of the markdown file to update the `events` page using the calendar information every day with a `cron` job on github actions.

You can see /adjust the file here for your reference:
https://github.com/UNopenGIS/smartmaps/blob/main/.github/workflows/update_events.yml
 
And the accompanying Python file:
https://github.com/UNopenGIS/smartmaps/blob/main/.scripts/events_updater.py

**Comment by hfu** [comment]
Wow, this great. Thank you!

**Comment by albertkun** [comment]
You are welcome! By the way, unrelated note, but did you get an email fromthe foss4g asia list from me? I've been trying to change my presentation day to be on a different day many times and there's been no reply 😭

**Comment by hfu** [comment]
@albertkun No, I haven't received an email you mentioned. I do not actually know when my presentation will be as of now...

**Comment by albertkun** [comment]
@hfu haha.. ok, thank you for letting me know! is your presentation/keynote not listed on this time table? :scream: https://foss4g.asia/2023/wp-content/uploads/2023/10/231021_FOSS4G-Asia-2023-Seoul_Time-Table-1.jpg

**Comment by hfu** [comment]
Not very sure about the schedule yet, but I am involved in the conference 👍🏻
