### ISSUE TITLE
Let's add updated social preview image

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/smartmaps#21]
Let's add updated social preview image https://github.com/UNopenGIS/7/issues/154#issuecomment-1556559961 to https://unopengis.github.io/smartmaps/about/brand. 

> @albertkun, could you handle this?

**Comment by albertkun** [comment]
I just added it under brand: 

- English: https://github.com/UNopenGIS/smartmaps/blob/main/docs/about/brand.md

- Japanese: https://github.com/UNopenGIS/smartmaps/blob/main/i18n/ja/docusaurus-plugin-content-docs/current/about/brand.md

Sorry for the slow reply! The school term is closing in 2 weeks! :(

**Comment by hfu** [comment]
@albertkun Thanks you!
