### ISSUE TITLE
Document Design System colors

### ISSUE THREAD

**Issue by albertkun** [UNopenGIS/smartmaps#36]
Based off of the earlier issue #33 a color scheme was created.

### Purpose

Make it easier to recognize our group and our initiatives.

#### Implementation

Create a page to document the following color choices:
|Type|Color|Hex|Purpose
|-----|------|----|--------
|Primary|Blue|`#5c81b8`|Used to represent the whole UN Smart Maps and `open license`
|Accent|Green|`#97be84`|Used to represent the `open community`
|Tertiary|Red|`#de8181`|Used to represent `open practice`

**Comment by hfu** [comment]
With a little help with an LLM, I created a description of this color scheme. Not technically confirmed! 

## UN Smart Maps Color Scheme
The UN Smart Maps Color Scheme is comprised of three key colors: Smart Blue, Collaboration Green, and Innovation Red. Each color is carefully selected to visually represent the values and principles of the UN Smart Maps Group and its initiatives, fostering a sense of identity and unity within our community while facilitating recognition of our work and objectives.

- Smart Blue: Smart Blue (RGB: rgb(92, 129, 184), #5c81b8) represents the intelligent and sophisticated approach of the UN Smart Maps group. It symbolizes innovation, clarity, and the open exchange of knowledge and resources within our community.

- Collaboration Green: Collaboration Green (RGB: rgb(151, 190, 132), #97be84) signifies the spirit of cooperation and unity within our community. It reflects our commitment to working together across diverse backgrounds and disciplines to achieve common goals and address global challenges.

- Innovation Red: Innovation Red (RGB: rgb(222, 129, 129), #de8181) embodies our commitment to innovation and forward-thinking practices in geospatial technology. It represents our willingness to embrace new ideas, methodologies, and technologies to improve decision-making and drive positive change worldwide.

These colors, Smart Blue, Collaboration Green, and Innovation Red, together constitute the UN Smart Maps Color Scheme. They are integral to our visual identity and are utilized across various platforms to represent our organization and its mission effectively.

**Comment by albertkun** [comment]
Looks great! Should I add this to the brand guidelines?

**Comment by hfu** [comment]
@albertkun I appreciate it if you could! 
I love using this color scheme. I am using the color in my current project, too. ;-) 
https://observablehq.com/d/cd3f9c8252ca19c6

**Comment by albertkun** [comment]
@hfu looks great in practice! i have added it in both the English and Japanese side:

https://unopengis.github.io/smartmaps/about/brand/#un-smart-maps-color-scheme

https://unopengis.github.io/smartmaps/ja/about/brand/#%E8%89%B2%E3%81%AE%E3%82%B9%E3%82%AD%E3%83%BC%E3%83%A0

**Comment by hfu** [comment]
@albertkun Wow, thanks! This is practcal and convenient at least for me!

**Comment by albertkun** [comment]
@hfu you are welcome! and that's great! we can probably close this issue!

**Comment by hfu** [comment]
@albertkun Yes, let's close this issue. Thank you so much!
