### ISSUE TITLE
Update Japanese translations in Python script

### ISSUE THREAD

**Issue by albertkun** [UNopenGIS/smartmaps#72]
Thanks to @asahina820 's translations, we should update the Python script so that the new files have the same better translation! 

There are two lines that need to be changed:

https://github.com/UNopenGIS/smartmaps/blob/fce095ec9a9174455b855caaa6adedd58b1a4791/.scripts/events_updater.py#L132

**Comment by asahina820** [comment]
@albertkun 
I read this python script!
I understood that this script works to create an event list page and detail pages for each event in the `events` folder.

I'm going to fix the header of the event list page.

https://github.com/UNopenGIS/smartmaps/blob/00aace64af8cf33b774679d05edda01b3abc5254/.scripts/events_updater.py#L132

I'll change, 

```
f_i18n.write("| イベント | 日付 |時刻| リンク |\n")
```

What do you think?
